"""Initial Migration

Revision ID: e4a979e7d79a
Revises: 
Create Date: 2025-06-07 17:32:22.646921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a979e7d79a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_short_name'), 'companies', ['short_name'], unique=True)
    op.create_table('custom_ui_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=True),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('accent_color', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('default_language', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', name='http_method_enum'), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_method'), 'endpoints', ['method'], unique=False)
    op.create_index(op.f('ix_endpoints_route'), 'endpoints', ['route'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_description'), 'groups', ['description'], unique=True)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_description'), 'permissions', ['description'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=1024), nullable=True),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('company_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('users_allowed', sa.Integer(), nullable=False),
    sa.Column('licensed_expiration_date', sa.DateTime(), nullable=False),
    sa.Column('custom_settings_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['custom_settings_id'], ['custom_ui_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_configurations_company_id'), 'company_configurations', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_configurations_custom_settings_id'), 'company_configurations', ['custom_settings_id'], unique=True)
    op.create_table('company_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_groups_company_id'), 'company_groups', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_groups_granted_by'), 'company_groups', ['granted_by'], unique=False)
    op.create_table('group_endpoint_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_endpoint_permissions_endpoint_id'), 'group_endpoint_permissions', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_group_endpoint_permissions_granted_by'), 'group_endpoint_permissions', ['granted_by'], unique=False)
    op.create_index(op.f('ix_group_endpoint_permissions_group_id'), 'group_endpoint_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_endpoint_permissions_permission_id'), 'group_endpoint_permissions', ['permission_id'], unique=False)
    op.create_table('group_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_permissions_granted_by'), 'group_permissions', ['granted_by'], unique=False)
    op.create_index(op.f('ix_group_permissions_group_id'), 'group_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_permissions_permission_id'), 'group_permissions', ['permission_id'], unique=False)
    op.create_table('user_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_companies_company_id'), 'user_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_companies_granted_by'), 'user_companies', ['granted_by'], unique=False)
    op.create_index(op.f('ix_user_companies_group_id'), 'user_companies', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_companies_user_id'), 'user_companies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_companies_user_id'), table_name='user_companies')
    op.drop_index(op.f('ix_user_companies_group_id'), table_name='user_companies')
    op.drop_index(op.f('ix_user_companies_granted_by'), table_name='user_companies')
    op.drop_index(op.f('ix_user_companies_company_id'), table_name='user_companies')
    op.drop_table('user_companies')
    op.drop_index(op.f('ix_group_permissions_permission_id'), table_name='group_permissions')
    op.drop_index(op.f('ix_group_permissions_group_id'), table_name='group_permissions')
    op.drop_index(op.f('ix_group_permissions_granted_by'), table_name='group_permissions')
    op.drop_table('group_permissions')
    op.drop_index(op.f('ix_group_endpoint_permissions_permission_id'), table_name='group_endpoint_permissions')
    op.drop_index(op.f('ix_group_endpoint_permissions_group_id'), table_name='group_endpoint_permissions')
    op.drop_index(op.f('ix_group_endpoint_permissions_granted_by'), table_name='group_endpoint_permissions')
    op.drop_index(op.f('ix_group_endpoint_permissions_endpoint_id'), table_name='group_endpoint_permissions')
    op.drop_table('group_endpoint_permissions')
    op.drop_index(op.f('ix_company_groups_granted_by'), table_name='company_groups')
    op.drop_index(op.f('ix_company_groups_company_id'), table_name='company_groups')
    op.drop_table('company_groups')
    op.drop_index(op.f('ix_company_configurations_custom_settings_id'), table_name='company_configurations')
    op.drop_index(op.f('ix_company_configurations_company_id'), table_name='company_configurations')
    op.drop_table('company_configurations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_description'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_description'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_endpoints_route'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_method'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_table('custom_ui_settings')
    op.drop_index(op.f('ix_companies_short_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
